<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: hello.proto

namespace Demo\Api\V1;

use Mix\Grpc;
use Mix\Grpc\Context;

interface HelloInterface extends Grpc\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "demo.api.v1.Hello";

    /**
    * @param Context $context
    * @param HelloReq $request
    * @return HelloResp
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function sayHello(Context $context, HelloReq $request): HelloResp;
}
