<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: hello.proto

namespace Demo\Api\V1;

use Mix\Grpc;
use Mix\Grpc\Context;

class HelloClient extends Grpc\Client\AbstractClient
{
    /**
    * @param Context $context
    * @param HelloReq $request
    * @param array $options
    * @return HelloResp
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function sayHello(Context $context, HelloReq $request): HelloResp
    {
        return $this->_simpleRequest('/demo.api.v1.Hello/sayHello', $context, $request, new HelloResp());
    }
}
